name: qisasi_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_tts: ^4.0.2
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.18.0  
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  animate_do: ^3.3.4
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # 1. أضفنا حزمة توليد الأيقونات هنا
  flutter_launcher_icons: ^0.13.1 

# 2. إعدادات أيقونة التطبيق (تأكد من المحاذاة والمسافات البادئة)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pic/logo.png" # مسار صورتك هنا
  min_sdk_android: 21 # يتوافق مع إعدادات الـ SDK لتطبيقك

flutter:
  uses-material-design: true
  assets:
    - assets/images/covers/
    - assets/images/animals/
    - assets/images/characters/
    - assets/images/locations/
    - assets/images/moods/
    - assets/images/pic/
    - assets/images/avatars/
    - assets/stories_data/stories.json